edition = "2024"
# max_width = 100
chain_width = 80
use_small_heuristics = "Max"
# match_arm_blocks = false
# group_imports = "One"
reorder_imports = true
# merge_imports = true
# imports_layout = "Horizontal"
# overflow_delimited_expr = true
